# Taps
tap "blackfireio/blackfire"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# Brews
brew "ack"
brew "ansible"
brew "ansible-lint"
brew "bat"
brew "bash"
brew "bash-completion2"
brew "blackfireio/blackfire/blackfire-agent"
brew "blackfireio/blackfire/blackfire-php72"
brew "byobu"
brew "coreutils"
brew "curl"
brew "diffoscope"
brew "dnscrypt-proxy"
brew "dnsmasq", restart_service: true
brew "editorconfig"
brew "ffmpeg"
brew "gnutls"
brew "gnupg"
brew "git"
brew "goaccess"
brew "graphviz"
brew "htop"
brew "hydra"
brew "i2p"
brew "jq"
brew "less"
brew "lynis"
brew "mas"
brew "mitmproxy"
brew "nikto"
brew "nginx", restart_service: true
brew "nmap"
brew "node"
brew "nyx"
brew "openssl"
brew "ocproxy"
brew "openconnect"
brew "openssh"
brew "php", restart_service: true
brew "plantuml"
brew "parallel"
brew "pv"
brew "postgresql", restart_service: true
brew "ponysay"
brew "python"
brew "redis", restart_service: true
brew "shellcheck"
brew "skipfish"
brew "speedtest_cli"
brew "sqlmap"
brew "swift"
brew "swiftlint"
brew "sysdig"
brew "sshfs"
brew "tmux"
brew "torsocks"
brew "tor", args: ["devel", "with-libscrypt"]
brew "xz"
brew "yarn"
brew "youtube-dl"

# Casks
cask "adium"
cask "bitbar"
cask "copyq"
cask "dash"
cask "dropbox"
cask "docker"
cask "emacs"
cask "font-fira-code"
cask "google-chrome"
cask "gpg-suite"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "insomnia"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keepassxc"
cask "minikube"
cask "mysqlworkbench"
cask "origami-studio"
cask "osxfuse"
cask "openconnect-gui"
cask "owasp-zap"
cask "postman"
cask "protonvpn"
cask "r-app"
cask "rstudio"
cask "safari-technology-preview"
cask "slack"
cask "spectacle"
cask "spotify"
cask "tableplus"
cask "transmission"
cask "tor-browser"
cask "tunnelblick"
cask "vlc"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "wireshark"

# MAS
mas "Amphetamine", id: 937984704
mas "Avira Security", id: 1376508752
mas "DrCleaner", id: 921458519
mas "DrUnarchiver", id: 1127253508
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Speedtest", id: 1153157709
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
