---

- name: Activate safari debug menu by default
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
    state: present

- name: Disable smart quotes as they’re annoying when typing code
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Set a blazingly fast keyboard repeat rate
  osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
    state: present

- name: Set a blazingly fast keyboard repeat rate
  osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15
    state: present
